[project]
name = "uwNerf"
version = "0.1.1"

dependencies = [
    "nerfstudio" 
]

[tool.setuptools.packages.find]
include = ["uwNerf*"]

[project.entry-points.'nerfstudio.method_configs']
uwnerf = 'uwNerf.uwNerfConfig:uwNerf'